### ISSUE TITLE
maxOccurs=1 lead to List

### ISSUE THREAD

**Issue by kronos72it** [highsource/hyperjaxb3#82]
my xsd appear as in attached file , then is ROOT  1-->1 Header   but when I build project , the hyperjaxb3 create 

`@ManyToOne(targetEntity = HeaderType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "HEADER_IRIDE_HJID")
    public HeaderType getHeader() {
![manytoone](https://github.com/highsource/hyperjaxb3/assets/14057059/30bb2d54-9845-4fc2-bb6d-5cf52ffe4398)

        return header;
    }`

it's my mistake or a bug ? I expect a OneToOne annotation because xsd tell ROOT can have only 1 header !

**Comment by laurentschoelens** [comment]
Hi @kronos72it 

Hyperjaxb3 has been merged in [jaxb-tools](https://github.com/highsource/jaxb-tools) repository.

I guess you already asked this in SO (since it's reminding me something) but for reference :
It's normal behaviour since XSD only provide one-way relationship between your ROOT object and the HEADER objects, saying that one Root Object has only one Header Object.

But you don't have any information about the reverse link between Header and Root object.
Does one Header belongs to only one Root Object ? Or can you have the same Header object into 2 differents Root Objects ?

Since plugin can't decide, it creates the default relationship which is a `@ManyToOne` relationship (one header can be used by multiples Root objects)

You can find the documentation in wiki's page here : https://github.com/highsource/jaxb-tools/wiki/HyperJAXB3-Reference-Single-Page#mapping-as-one-to-one
